# -*- coding: utf-8 -*-
"""text to speech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Ht9MY9SkR3q_nLqqR0UJR8q6ibMEIEh
"""

#text to speech
# Text to speech
from gtts import gTTS
import gradio as gr

def text_to_speech(text):
  tts=gTTS(text=text,lang="en")
  output_file="output.mp3"
  tts.save(output_file)
  return output_file

demo=gr.Interface(fn=text_to_speech,
                  inputs=gr.Textbox(lines=5,label="Enter Text"),
                  outputs=gr.Audio(label="Speech"),
                  title="Text-to-Speech"
                  )
demo.launch()